### PR TITLE
Fixed the parser when there is a newline escape followed by space

### LINKED ISSUE #35: Cannot parse if line ends with linebreak and space
```Dockerfile
FROM centos:centos7

RUN yum -y install --setopt=tsflags=nodocs epel-release && \ 
    yum -y update && yum clean all
```

There is a space ` ` after `\`

```bash
$ integration-tests/parseFile Dockerfile.break
Left (TrivialError (SourcePos {sourceName = "Dockerfile.break", sourceLine = Pos 4, sourceColumn = Pos 5} :| []) (Just (Tokens ('y' :| ""))) (fromList [Tokens ('#' :| ""),Label ('A' :| "DD"),Label ('A' :| "RG"),Label ('C' :| "MD"),Label ('C' :| "OPY"),Label ('E' :| "NTRYPOINT"),Label ('E' :| "NV"),Label ('E' :| "XPOSE"),Label ('F' :| "ROM"),Label ('H' :| "EALTHCHECK"),Label ('L' :| "ABEL"),Label ('M' :| "AINTAINER"),Label ('O' :| "NBUILD"),Label ('R' :| "UN"),Label ('S' :| "HELL"),Label ('S' :| "TOPSIGNAL"),Label ('U' :| "SER"),Label ('V' :| "OLUME"),Label ('W' :| "ORKDIR"),Label ('t' :| "he rest of a new line followed by the next instruction"),EndOfInput]))
```

It wasn't catched in integration tests because error message has changed 
https://github.com/hadolint/language-docker/blob/9a0e80fe0dfec001d2c02310d0c1798c10289297/integration-tests/parse_files.sh#L112

### PR DESCRIPTION
**Pull request by lorenzo**
Also exports more things that I mised in the previous release

fixes #35

### CODE REVIEW

File: integration-tests/parse_files.sh [hunk 1]
```diff
@@ -109,8 +109,11 @@ function parse_dockerfiles() {
 	if [[ "$BLACKLIST" == *$dockerfile* ]]; then
 		continue;
 	fi
-        if ./parseFile "$dockerfile" | grep -a1 unexpected; then
-            result="false"
+
+        if ./parseFile "$dockerfile" > /dev/null; then
+	    echo "$dockerfile"
+        else
+	    result="false"
```
Comment (zemanlx) [inline integration-tests/parse_files.sh]: image
Can you please fix indentation? Some of them are tabs and some spaces.

Comment (zemanlx) [reply integration-tests/parse_files.sh]: I would prefer spaces if you don't mind.
